services:
  mysql:
    image: mysql:8.4
    container_name: student-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Mouhamed10082006
      MYSQL_DATABASE: student_management
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pMouhamed10082006"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: student-app
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/student_management?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Mouhamed10082006
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
